# Generated by Django 5.2.8 on 2026-01-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'paymant'), ('processing', 'process'), ('shipped', 'sending items to  post'), ('deleverd', 'deliverd')], default='pending', max_length=50),
        ),
    ]
